/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Front;

import Back.Mesa;
import Back.ItemPedido;
import Back.GestorRestaurante;
import Back.Factura;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO
 */
public class FacturaGenerar extends javax.swing.JPanel {
    DefaultListModel modelo = new DefaultListModel();
    /**
     * Creates new form FacturaGenerar
     */
    public FacturaGenerar() {
        initComponents();
         jList1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Generar factura");

        jLabel2.setText("Número de mesa");

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // Se eliminan todos los elementos del modelo
modelo.removeAllElements();

    // Se inicializa la variable para almacenar el número de mesa
    int numeroMesa = 0;

    // Se verifica si se ha ingresado un número de mesa
    if (jTextField1.getText() != null) {
        try {
            // Se intenta convertir el valor del campo de texto a un número entero (número de mesa)
            numeroMesa = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            // Si el valor ingresado no es un número válido, se muestra un mensaje de error
            JOptionPane.showMessageDialog(null, "Número de pedido inválido");
        }

        // Se busca la mesa correspondiente al número ingresado
        if (Mesa.buscarBinario(numeroMesa) != null) {
            // Si se encuentra la mesa, se obtiene su pedido y se agregan los ítems del pedido al modelo
            Mesa m = Mesa.buscarBinario(numeroMesa);
            for (ItemPedido p : m.getPedidoMesa().getItems()) {
                modelo.addElement(p);
            }

            // Se genera la factura correspondiente a la mesa y se agrega al modelo
            Factura f = GestorRestaurante.generarFactura(m);
            modelo.addElement(f);
        } else {
            // Si no se encuentra la mesa, se muestra un mensaje indicando que no se encontró el pedido
            JOptionPane.showMessageDialog(null, "No se encontró el pedido");
        }
    } else {
        // Si no se ha ingresado un número de mesa, se muestra un mensaje de advertencia
        JOptionPane.showMessageDialog(null, "Debe ingresar el número del pedido");
    }

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
