/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Front;

import Back.Producto;
import Back.Plato;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO
 */
public class MenuAgregarItem extends javax.swing.JPanel {

    /**
     * Creates new form MenuAgregarItem
     */
    public MenuAgregarItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        platoBoton = new javax.swing.JRadioButton();
        productoBoton = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Agregar platos o productos al menú");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de item");

        buttonGroup1.add(platoBoton);
        platoBoton.setText("Plato");

        buttonGroup1.add(productoBoton);
        productoBoton.setText("Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(platoBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productoBoton))
                            .addComponent(precio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(platoBoton)
                    .addComponent(productoBoton))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //ArrayList <ItemMenu> listaItemsMenu = null;
        // Se asigna cada botón de radio al grupo de botones
    buttonGroup1.add(platoBoton);
    buttonGroup1.add(productoBoton);

    // Se declara la variable para almacenar el precio
    double precioP;

    // Se verifica si los campos de texto están vacíos
    if ((jTextField1.getText().isEmpty()) || (precio.getText().isEmpty())) {
        // Si algún campo está vacío, muestra un mensaje indicando que se deben llenar todos los campos
        JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
    } else {
        try {
            // Se intenta convertir el valor del campo de precio a un número decimal
            precioP = Double.parseDouble(precio.getText());

            // Se verifica cuál botón está seleccionado
            if (platoBoton.isSelected()) {
                // Si está seleccionado el botón de plato, se crea un nuevo plato y se muestra un mensaje de confirmación
                Plato item = new Plato((jTextField1.getText()), precioP);
                JOptionPane.showMessageDialog(null, "El plato ha sido agregado al menú\n" + item);

                // Se obtiene la lista actual de platos y se agrega el nuevo plato
                ArrayList<Plato> p = Plato.listarBinario();
                p.add(item);

                // Se actualiza el archivo binario con la lista actualizada de platos
                Plato.escribirBinario(p);
            } else if (productoBoton.isSelected()) {
                // Si está seleccionado el botón de producto, se crea un nuevo producto y se muestra un mensaje de confirmación
                Producto item = new Producto((jTextField1.getText()), precioP);
                JOptionPane.showMessageDialog(null, "El producto ha sido agregado al menú\n" + item);

                // Se obtiene la lista actual de productos y se agrega el nuevo producto
                ArrayList<Producto> p = Producto.listarBinario();
                p.add(item);

                // Se actualiza el archivo binario con la lista actualizada de productos
                Producto.escribirBinario(p);
            } else {
                // Si no se ha seleccionado ningún tipo de item, muestra un mensaje indicando que se debe escoger
                JOptionPane.showMessageDialog(null, "Debe escoger el tipo de item");
            }
        } catch (NumberFormatException e) {
            // Si el precio ingresado no es un número válido, muestra un mensaje de error
            JOptionPane.showMessageDialog(null, "El precio ingresado es inválido");
        } finally {
            // Se limpian los campos de texto después de realizar las operaciones
            jTextField1.setText("");
            precio.setText("");
        }
    }

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton platoBoton;
    private javax.swing.JTextField precio;
    private javax.swing.JRadioButton productoBoton;
    // End of variables declaration//GEN-END:variables
}
