/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Front;

import Back.Reserva;
import Back.Mesa;
import Back.ClientePreferencial;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO
 */
public class ReservaCrear extends javax.swing.JPanel {

    /**
     * Creates new form ReservaCrear
     */
    public ReservaCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nueva reserva");

        jLabel2.setText("No. de identificación del cliente");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Número de mesa");

        jLabel4.setText("Fecha (AAAA/MM/DD)");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Número de reserva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField1))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Inicialización de variables para los datos de la reserva
        int numeroReserva = 0;
        int tarjetaCliente = 0;
        int numeroMesa = 0;
        String fecha = null;
        Mesa m = null;

        // Verificación de que los campos no estén vacíos
        if ((jTextField1.getText() != null) && (jTextField2.getText() != null) && (jTextField3.getText() != null) && 
                (jTextField4.getText() != null)) {
            try {
                // Obtención de los datos de los campos de texto
                numeroReserva = Integer.parseInt(jTextField1.getText());
                tarjetaCliente = Integer.parseInt(jTextField2.getText());
                numeroMesa = Integer.parseInt(jTextField3.getText());
                fecha = jTextField4.getText();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Datos inválidos");
            }

            // Verificación de que el número de reserva no esté en uso
            if (Reserva.buscarBinario(numeroReserva) == null) {
                // Verificación de existencia del cliente preferencial
                if ((ClientePreferencial.buscarBinario(tarjetaCliente) != null)) {
                    ClientePreferencial c = ClientePreferencial.buscarBinario(tarjetaCliente);
                    m = Mesa.buscarBinario(numeroMesa);

                    // Si la mesa no existe, se crea una nueva instancia
                    if (m == null) {
                        m = new Mesa(numeroMesa);
                    }

                    // Validación del formato de fecha ingresado
                    if (Reserva.validarFormatoFecha(fecha)) {
                        // Verificación de disponibilidad de la mesa en la fecha seleccionada
                        if (Reserva.verificarDisponibilidadMesa(m, Reserva.inicializarCalendar(fecha))) {
                            // Creación y almacenamiento de la reserva
                            ArrayList<Reserva> r = Reserva.listarBinario();
                            r.add((new Reserva(numeroReserva, c, m, fecha)));
                            Reserva.escribirBinario(r);
                            JOptionPane.showMessageDialog(null, "Reserva creada con éxito");
                        } else {
                            JOptionPane.showMessageDialog(null, "La mesa ya se encuentra reservada en la fecha ingresada");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "La fecha no tiene el formato correcto 'AAAA/MM/DD'");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró al cliente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El número de reserva ya se encuentra en uso");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }

        // Limpieza de los campos de texto después de la operación
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
